version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-taller
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Nalita.48
      MYSQL_DATABASE: proyectoastaller
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pNalita.48"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ../backed
      dockerfile: Dockerfile
    container_name: backTaller-backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/proyectoastaller
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Nalita.48
      JPA_DDL_AUTO: update
      JPA_SHOW_SQL: "true"
    expose:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: agorasoft-frontend
    expose:
      - "80"

  proxy:
    image: nginx:1.27-alpine
    container_name: agorasoft-proxy
    depends_on:
      - backend
      - frontend
    ports:
      - "8085:80"
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf:ro
