version: "3.9"

services:
  backend:
    build:
      context: ../backed
      dockerfile: Dockerfile
    container_name: agorasoft-backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/AgoraSoft
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: contrasena
      JPA_DDL_AUTO: update
      JPA_SHOW_SQL: "true"

    expose:
      - "8080"
    # Descomenta para depurar directamente sin proxy (no recomendado cuando uses proxy):
    # ports:
    #   - "8080:8080"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: agorasoft-frontend
    expose:
      - "80"
    # Igual que arriba: solo si quieres verlo directo sin proxy:
    # ports:
    #   - "4201:80"

  proxy:
    image: nginx:1.27-alpine
    container_name: agorasoft-proxy
    depends_on:
      - backend
      - frontend
    ports:
      - "8085:80"
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf:ro