version: "3.9"

services:
  backend:
    build:
      context: ../backed
      dockerfile: Dockerfile
    container_name: backTaller-backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres.kbzpuizmuxvyzdmuwnth
      SPRING_DATASOURCE_PASSWORD: Taller.Arqui1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: agorasoft-frontend
    expose:
      - "80"
    restart: always

  proxy:
    image: nginx:1.27-alpine
    container_name: agorasoft-proxy
    depends_on:
      - backend
      - frontend
    ports:
      - "8085:80"
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
